site_name: SAGE documentation
theme:
  name: material
  palette:
    primary: black
    accent: deep orange
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - offline
  - search

# Navigation
nav:
  - About: index.md
  - Project's structure: ProjectStructure.md
  - User manual:
    - How To: UserManual/HowTo.md
    - Config Files: UserManual/Config.md
    - Observation Generators: UserManual/Generators.md
